{"event": "Watching for file changes with StatReloader", "level": "info", "logger": "django.utils.autoreload", "timestamp": "2023-05-02T09:26:17.989756Z", "user": "3c300e63-734e-4f09-9d55-f0c40554e52b"}
{"event": "Pika version 1.1.0 connecting to ('15.206.140.228', 5671)", "level": "info", "logger": "pika.adapters.utils.connection_workflow", "timestamp": "2023-05-02T09:26:18.317778Z", "user": "4cbcfd71-6111-47da-a5b7-2eb121f85544"}
{"event": "Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.0.3', 33584), raddr=('15.206.140.228', 5671)>", "level": "info", "logger": "pika.adapters.utils.io_services_utils", "timestamp": "2023-05-02T09:26:18.343649Z", "user": "15605865-a18a-45a9-821b-ead63cf37c7b"}
{"event": "SSL handshake completed successfully: <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.0.3', 33584), raddr=('15.206.140.228', 5671)>", "level": "info", "logger": "pika.adapters.utils.io_services_utils", "timestamp": "2023-05-02T09:26:18.397773Z", "user": "76683010-ae0a-43ed-b827-3742c8c6260d"}
{"event": "Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f40a1f0c700>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f40a1f0c700> params=<URLParameters host=puffin.rmq2.cloudamqp.com port=5671 virtual_host=nhvdbbep ssl=True>>).", "level": "info", "logger": "pika.adapters.utils.connection_workflow", "timestamp": "2023-05-02T09:26:18.399037Z", "user": "de860ca4-9c87-4cc0-9f5a-901b5b047537"}
{"event": "AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f40a1f0c700> params=<URLParameters host=puffin.rmq2.cloudamqp.com port=5671 virtual_host=nhvdbbep ssl=True>>", "level": "info", "logger": "pika.adapters.utils.connection_workflow", "timestamp": "2023-05-02T09:26:18.736104Z", "user": "06c66004-1cfa-4a12-a834-1c54698ebdab"}
{"event": "AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f40a1f0c700> params=<URLParameters host=puffin.rmq2.cloudamqp.com port=5671 virtual_host=nhvdbbep ssl=True>>", "level": "info", "logger": "pika.adapters.utils.connection_workflow", "timestamp": "2023-05-02T09:26:18.736848Z", "user": "cf729336-69bd-4625-903a-4f15cb9d8ade"}
{"event": "Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f40a1f0c700> params=<URLParameters host=puffin.rmq2.cloudamqp.com port=5671 virtual_host=nhvdbbep ssl=True>>", "level": "info", "logger": "pika.adapters.blocking_connection", "timestamp": "2023-05-02T09:26:18.737676Z", "user": "f814f388-d35e-44b5-ad38-9fb23bd80404"}
{"event": "Created channel=1", "level": "info", "logger": "pika.adapters.blocking_connection", "timestamp": "2023-05-02T09:26:18.738710Z", "user": "bcb7c422-1d25-4fb0-b0e8-f2b6cfdb18c5"}
{"event": "Internal Server Error: /api/products/77", "level": "error", "logger": "django.request", "timestamp": "2023-05-02T09:30:04.705599Z", "user": "92741634-988e-42aa-a8d0-887afeedf990", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py\", line 47, in inner\n    response = get_response(request)\n  File \"/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py\", line 179, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py\", line 54, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py\", line 125, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/app/products/views.py\", line 25, in retrieve\n    product = Product.objects.get(id=pk)\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/query.py\", line 429, in get\n    raise self.model.DoesNotExist(\nproducts.models.Product.DoesNotExist: Product matching query does not exist."}
{"event": "Internal Server Error: /api/products/399", "level": "error", "logger": "django.request", "timestamp": "2023-05-02T09:30:28.032694Z", "user": "0c3dba73-bc03-466f-8dbf-e01e6b46cd55", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py\", line 47, in inner\n    response = get_response(request)\n  File \"/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py\", line 179, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py\", line 54, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py\", line 125, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/app/products/views.py\", line 38, in destroy\n    product = Product.objects.get(id=pk) # Fetching the record - given ID\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/query.py\", line 429, in get\n    raise self.model.DoesNotExist(\nproducts.models.Product.DoesNotExist: Product matching query does not exist."}
